import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Body from "./components/Body";
import Car from "./components/Car";
import Cards from "./components/Cards";
import Footer from "./components/Footer";
import Header from "./components/Header";
import Accrod from "./components/Accrod";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Header/>
      <Body/>
      <Car/>
      <Cards/>
      <Accrod/>
      <Footer/>
        
      </body>
    </html>
  );
}
